// <auto-generated />
using CMS_HERA_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS_HERA_MVC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201209120517_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS_HERA_MVC.Models.Taxe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_Taxe")
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<int>("Status_Taxe")
                        .HasColumnType("int");

                    b.Property<string>("Taxe_Col")
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<float>("Valeur_Taxe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Taxe");
                });
#pragma warning restore 612, 618
        }
    }
}
